name:  Display information about GitHub Actions CPU architecture       
on: workflow_dispatch
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - run: curl https://pyenv.run | bash
      
    
